--- #YAML:1.0
name:               Perl-Version
version:            1.011
abstract:           Parse and manipulate Perl version strings
author:
    - Andy Armstrong <andy@hexten.net>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    File::Slurp:   9999.12
    Getopt::Long:  2.34
    Pod::Usage:    1.3
    Scalar::Util:  0
    Test::More:    0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
