--- #YAML:1.0
name:                Perl-Version
version:             v0.0.7
abstract:            Parse and manipulate Perl version strings
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    File::Slurp:                   9999.12
    Getopt::Long:                  2.34
    Pod::Usage:                    1.3
    Scalar::Util:                  0
    Test::More:                    0
    version:                       0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Andy Armstrong <andy@hexten.net>
