---
abstract: 'Parse and manipulate Perl version strings'
author:
  - 'Andy Armstrong <andy@hexten.net>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Perl-Version
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  Data::Dumper: 0
  File::Slurp::Tiny: 0
  Getopt::Long: 2.34
  Pod::Usage: 1.3
  Scalar::Util: 0
  Test::More: 0
version: 1.013
